/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as KnowledgeKbIdRouteImport } from './routes/knowledge.$kbId'
import { Route as CockpitConversationIdRouteImport } from './routes/cockpit.$conversationId'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents.$agentId.index'
import { Route as AgentsAgentIdEditRouteImport } from './routes/agents.$agentId.edit'

const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const KnowledgeKbIdRoute = KnowledgeKbIdRouteImport.update({
  id: '/$kbId',
  path: '/$kbId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CockpitConversationIdRoute = CockpitConversationIdRouteImport.update({
  id: '/cockpit/$conversationId',
  path: '/cockpit/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdEditRoute = AgentsAgentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/conversations': typeof ConversationsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/cockpit/$conversationId': typeof CockpitConversationIdRoute
  '/knowledge/$kbId': typeof KnowledgeKbIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/agents/new': typeof AgentsNewRoute
  '/cockpit/$conversationId': typeof CockpitConversationIdRoute
  '/knowledge/$kbId': typeof KnowledgeKbIdRoute
  '/agents': typeof AgentsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/conversations': typeof ConversationsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/cockpit/$conversationId': typeof CockpitConversationIdRoute
  '/knowledge/$kbId': typeof KnowledgeKbIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/agents/$agentId/edit': typeof AgentsAgentIdEditRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/conversations'
    | '/knowledge'
    | '/agents/$agentId'
    | '/agents/new'
    | '/cockpit/$conversationId'
    | '/knowledge/$kbId'
    | '/agents/'
    | '/knowledge/'
    | '/agents/$agentId/edit'
    | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/agents/new'
    | '/cockpit/$conversationId'
    | '/knowledge/$kbId'
    | '/agents'
    | '/knowledge'
    | '/agents/$agentId/edit'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/conversations'
    | '/knowledge'
    | '/agents/$agentId'
    | '/agents/new'
    | '/cockpit/$conversationId'
    | '/knowledge/$kbId'
    | '/agents/'
    | '/knowledge/'
    | '/agents/$agentId/edit'
    | '/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ConversationsRoute: typeof ConversationsRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  CockpitConversationIdRoute: typeof CockpitConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/knowledge/$kbId': {
      id: '/knowledge/$kbId'
      path: '/$kbId'
      fullPath: '/knowledge/$kbId'
      preLoaderRoute: typeof KnowledgeKbIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/cockpit/$conversationId': {
      id: '/cockpit/$conversationId'
      path: '/cockpit/$conversationId'
      fullPath: '/cockpit/$conversationId'
      preLoaderRoute: typeof CockpitConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/edit': {
      id: '/agents/$agentId/edit'
      path: '/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AgentsAgentIdEditRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdEditRoute: typeof AgentsAgentIdEditRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdEditRoute: AgentsAgentIdEditRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeKbIdRoute: typeof KnowledgeKbIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeKbIdRoute: KnowledgeKbIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ConversationsRoute: ConversationsRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  CockpitConversationIdRoute: CockpitConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
